config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root "events#index"

  resources :events, :users, :event_attendees, :invites

  post '/invites/:id', to: 'invites#accept'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees

  has_many :invites, foreign_key: :invited_event_id
  has_many :invitees, through: :invites

  validates :place, presence: true
  validates :date, presence: true

  # def self.upcoming
  #   where("date > ?", Time.zone.now)
  # end

  # def self.past
  #   where("date < ?", Time.zone.now)
  # end

  scope :upcoming, -> { where("date > ?", Time.now) }
  scope :past, -> { where("date < ?", Time.now) }

  def pretty_date
    "#{date.month}-#{date.day}-#{date.year}"
  end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :invitee, class_name: "User"
  belongs_to :invited_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees

  has_many :invites, foreign_key: :invitee_id
  has_many :invited_event, through: :invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def require_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :require_login
  
  def show
    @event_attendee = EventAttendee.find(params[:id])
  end

  def index
    @event_attendees = EventAttendee.all
  end

  def create
    @event_attendee = EventAttendee.new(event_attendees_params)

    if @event_attendee.save
      redirect_to event_path(Event.find(params[:id]))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    event = Event.find(params[:id])
    @event_attendee = EventAttendee.find_by(attendee_id: "#{current_user.id}", attended_event_id: "#{event.id}")
    @event_attendee.destroy

    redirect_to event_path(event)
  end

  private

  def event_attendees_params
    params.require(:event_attendee).permit(:attended_event_id, :attendee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, except: [:index]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @invites = Invite.where("invited_event_id = ?", @event.id)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id

    # @event = current_user.attending_events.build(event_params)

    if @event.save
      flash[:notice] = 'Successfully created!'
      EventAttendee.create(attendee_id: current_user.id, attended_event_id: @event.id)
      redirect_to @event
    else
      flash.now[:alert] = "Oh no! Something went wrong!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = 'Successfully updated!'
      redirect_to @event
    else
      flash.now[:alert] = "Oh no! Something went wrong!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    flash[:notice] = 'Successfully deleted!'
    redirect_to root_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:date, :place, :title, :body)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    @invite = Invite.new(invites_params)

    if @invite.save
      flash[:notice] = "Invite sent!"
      redirect_to event_path(params[:invite][:invited_event_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @invite = Invite.where("invited_event_id = ?", params[:event_id]).and(Invite.where("invitee_id = ?", params[:user_id]))
    @invite.destroy_all

    flash[:alert] = 'Invite deleted!'
    redirect_back(fallback_location: root_path)
  end

  def accept
    @invite = Invite.find(params[:invite][:invite_id])
    EventAttendee.create(attended_event_id: params[:invite][:invited_event_id], attendee_id: current_user.id)
    @invite.destroy

    flash[:notice] = 'Accepted!'
    redirect_to event_path(params[:invite][:invited_event_id])
  end

  private

  def invites_params
    params.require(:invite).permit(:invitee_id, :invited_event_id, :invite_id)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendees/new.html.erb
error

app/views/events/edit.html.erb
<%= render "shared/navbar" %>

<%= render "shared/flash" %>

<div class="columns is-centered">
  <div class="column is-3">
    <h1 class="title m-5 mt-6">Edit Event:</h1>
  
    <%= render "shared/form" %>
  </div>
</div>

app/views/events/index.html.erb
<%= render "shared/navbar" %>

<%= render "shared/flash" %>

<div class="container">
  <div class="columns">
    <div class="column is-half has-text-centered mt-6 mb-6">
      <div class="is-size-1 mb-4">Upcoming:</div>
      <ul>
        <%= render "shared/column", :events => @events.upcoming %>
      </ul>
    </div>
  
    <div class="column is-half has-text-centered mt-6 mb-6">
      <div class="is-size-1 mb-4">Past:</div>
      <ul>
        <%= render "shared/column", :events => @events.past %>
      </ul>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render "shared/navbar" %>

<%= render "shared/flash" %>

<div class="columns is-centered">
  <div class="column is-3">
    <h1 class="title m-5 mt-6">New Event:</h1>
  
    <%= render "shared/form" %>
  </div>
</div>

app/views/events/show.html.erb
<%= render "shared/navbar" %>

<%= render "shared/flash" %>

<div class="container box mt-6">
  <div class="columns">
    <div class="column">
      <h2 class="is-size-4 has-text-centered">Details:</h2>
      <ul>
        <div class="container m-6">
          <li><%= "Location:  #{@event.place}" %></li>
          <li><%= "Date:  #{@event.pretty_date}" %></li>
          <li>Host: <%= link_to "#{@event.creator.name}", user_path(@event.creator.id)%> </li>
          <li class="pt-2 pb-2 mt-4"><%= "Details: #{@event.body}" %></li>
        </div>
      </ul>
    </div>

    <div class="column has-text-centered">
      <h2 class="is-size-4">Attendees:</h2>
      <ul>
        <div class="container mt-2">
          <% @event.attendees.each do |person| %>
            <li><%= link_to person.name, user_path(person.id) %></li>
          <% end %>
        </div>
      </ul>
    </div>

    <div class="column">
      <h2 class="is-size-4">Invitees:</h2>
      <ul>
        <div class="container mt-2">
          <% @event.invitees.each do |invitee| %>
            <li><%= link_to invitee.name, user_path(invitee.id) %></li>
          <% end %>
        </div>
      </ul>
    </div>

    <div class="column is-1 ml">
      <div class="container mt-3">



      <% if current_user == @event.creator %>
        <div class="dropdown is-hoverable mt-2 is-right">
          <div class="dropdown-trigger">
            <button class="button is-light is-rounded is-small">Invite</button>
          </div>
          <div class="dropdown-menu">
            <div class="dropdown-content">
              <% User.all.each do |user| %>
                <% if @event.invitees.include?(user) %>
                  <div class="dropdown-item">
                    <%= button_to "Uninvite #{user.name}", 
                        invite_path(event_id: @event.id, user_id: user.id ),
                        class: "button is-danger is-small", method: :delete %>
                  </div>
                <% elsif !@event.invitees.include?(user) && !@event.attendees.include?(user) %>
                  <div class="dropdown-item">
                    <%= button_to user.name, invites_path(invite: {invitee_id: user.id, invited_event_id: @event.id}), class: "button is-light is-small" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <% if @event.creator != current_user %>
          <% if @event.attendee_ids.include?(current_user.id) %>
            <%= button_to "Unattend", event_attendee_path(@event), class: "button is-danger is-small is-rounded", method: :delete%>
          <% else %>
            <%= button_to "Attend", event_attendees_path(event_attendee: {attended_event_id: @event.id, attendee_id: current_user.id}), class: 'button is-light is-rounded is-small mt-1' %>
          <% end %>
        <% end %>
      <% end %>
      

      </div>
    </div>
  </div>
  
  <% if current_user.id == @event.creator.id %>
    <div class="buttons are-small is-centered mt-6">
      <%= button_to "Edit", edit_event_path(@event), class: "button is-light is-rounded", method: :get %>
      <%= button_to "Delete", event_path(@event), class: "button is-danger is-rounded", method: :delete %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_column.html.erb
<% events.each do |event| %>
  <div class="card mb-6">
    <div class="card-header">
      <div class="card-header-title">
        <%= "#{event.title}: #{event.pretty_date}" %>
      </div>
    </div>
    <div class="card-content">
      <li><%= event.body %></li>
    </div>
    <div class="card-footer">
      <div class="card-footer-item"><%= link_to "View", event_path(event.id) %></div>
      <% if event.creator == current_user %>
        <div class="card-footer-item"><%= link_to "Edit", edit_event_path(event.id) %></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == "notice" %>
    <div class="notification is-primary">
      <div>
        <%= msg %>
      </div>
    </div>
  <% else %>
    <div class="notification is-danger">
      <div>
        <%= msg %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @event do |form| %>
  <div class="field box m-5">
    <%= form.label :title, "Title:", class: "label" %>
    <div class="control">
      <%= form.text_field :title, class: "input" %>
    </div>

    <%= form.label :place, "Location:", class: "label" %>
    <div class="control">
      <%= form.text_field :place, class: "input" %>
    </div>

    <%= form.label :date, "Time:", class: "label mt-2" %>
    <div class="control">
      <%= form.datetime_local_field :date, class: "input" %>
    </div>

    <%= form.label :body, "Description:", class: "label mt-2" %>
    <div class="control">
      <%= form.text_field :body, class: "textarea" %>
    </div>
    
    <%= form.submit "Submit", class: "button mt-5 is-light" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light">
  <div class="navbar-start">
    <h1 class="navbar-item title ml-5"><%= link_to "Private Events", root_path, class: "has-text-dark" %></h1>
  </div>
  <div class="navbar-end mr-5">
    <div class="navbar-item"><%= link_to "Home", root_path, class: "has-text-dark" %></div>
    <% if user_signed_in? %>
      <div class="navbar-item"><%= link_to "New Event", new_event_path,class: "has-text-dark" %></div>
      <div class="navbar-item "><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "has-text-dark" %></div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Profile
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
          <%= link_to "View", user_path(current_user.id), class: "has-text-dark ml-3" %>
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item"><%= link_to "Edit", edit_user_registration_path(current_user.id), class: "has-text-dark ml-3" %></a>
        </div>
      </div>

    <% else %>
      <div class="navbar-item"><%= link_to "Sign in", new_user_session_path, class: "has-text-dark" %></div>
      <div class="navbar-item"><%= link_to "Sign up", new_user_registration_path, class: "has-text-dark" %></div>
    <% end %>
  </div>
</nav>

app/views/users/show.html.erb
<%= render "shared/navbar" %>

<div class="columns m-4">
  <div class="column has-text-centered">
    <div class="box mt-6">
      <h3 class="is-size-4 mb-2">Created Events:</h3>
      <ul>
        <% @user.created_events.each do |event| %>
          <li><%= link_to "#{event.place}", event_path(event.id) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <div class="column has-text-centered">
    <div class="box mt-6">
      <h3 class="is-size-4 mb-2">Future Events:</h3>
      <% @user.attended_events.each do |event| %>
        <ul>
          <% if event.date > Time.now %>
          <li><%= link_to "#{event.place}", event_path(event.id) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  
  <div class="column has-text-centered">
    <div class="box mt-6">
      <h3 class="is-size-4 mb-2">Past Events:</h3>
      <% @user.attended_events.each do |event| %>
        <ul>
          <% if event.date < Time.now %>
          <li><%= link_to "#{event.place}", event_path(event.id) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="column is-2">
    <div class="box mt-6">
      <h3 class="is-size-4 mb-2">Invites:</h3>
      <% @user.invited_event.each do |event| %>
        <ul>
          <li>
            <div class="is-flex">
              <%= link_to event.title, event_path(event.id) %> --
              <%= button_to "Accept", 
              invite_path(invite: {invitee_id: @user.id, invited_event_id: event.id, invite_id: Invite.where("invitee_id = ?", @user.id).and(Invite.where("invited_event_id = ?", event.id)).ids[0]}), 
              method: :post %>
              <%= button_to "Decline", 
              invite_path(Invite.where("invitee_id = ?", @user.id).and(Invite.where("invited_event_id = ?", event.id)).ids[0]), 
              method: :delete %>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>